### ISSUE TITLE
Selenium::Firefox::Profile  can't set the preference

### ISSUE THREAD

**Issue by autodataming** [gempesaw/Selenium-Remote-Driver#240] opened 2016-01-06 03:04 UTC
```Perl
my $profile = Selenium::Firefox::Profile->new;
$profile->set_preference(
    'browser.startup.homepage' => 'http://www.googto.com',
    );

my $driver=Selenium::Firefox->new("profile"=>$profile);


sleep(20);
````
the above code failed.

-----------------------------------------
```Perl
my $profile = Selenium::Remote::Driver::Firefox::Profile->new();
$profile->set_preference(
   'browser.startup.homepage' => 'http://www.ping.com',
    );
my $driver=Selenium::Remote::Driver->new('firefox_profile' => $profile);


sleep(20);
#step2 login

```
the code successful. But before run the code, You must start the selenium
like this:
java -jar selenium-server.jar

**Comment by gempesaw** [comment] 2016-01-07 06:10
Thanks for the additional debugging information. Happily for us, when using `Selenium::Remote::Driver` as in your second example, the Selenium jar can handle all the Firefox profile configuration. 

In the first example, the bug that persists is exactly the same as in #239, so I'm closing this as a duplicate of that. Thanks!

**Closed by gempesaw** 2016-01-07 06:10 UTC
