### ISSUE TITLE
Selenium::Firefox throws error on find_element()

### ISSUE THREAD

**Issue by hornschorsch** [gempesaw/Selenium-Remote-Driver#299] opened 2016-12-13 14:36 UTC
Hello,

with Selenium-Remote-Driver-1.00 and the following script:

```
#!/usr/bin/perl -w
use Selenium::Firefox;

# Create a new instance of the driver
my $driver = Selenium::Firefox->new;

# Fetch a page
$driver->get("http://simsurfer.de/testapp/index.php");

# Print page title
my $title = $driver->get_title();
print "title1: $title\n";

# Find the element that's name attribute is "username".
my $inputElement = $driver->find_element_by_name("username");

# type in the username
$inputElement->send_keys("gast");
```

i get the following error:

```
$ xy.pl
title1: Simsurfer - TestApp
Use of uninitialized value in hash element at /usr/local/share/perl5/Selenium/Remote/ErrorHandler.pm line 126.
Error while executing command: findElement at /usr/local/share/perl5/Selenium/Remote/Driver.pm line 313.
 at /usr/local/share/perl5/Selenium/Remote/Driver.pm line 313.
 at /usr/local/share/perl5/Selenium/Remote/Finders.pm line 23.
```

Firefox is version 49.0, geckodriver 0.11.1, perl v5.18.1 on slackware 14.1.

If i use Selenium::Remote::Driver instead of Selenium::Firefox the script works, but i would prefer to use Selenium::Firefox without the selenium server.

Kind Regards,
Georg

**Comment by gempesaw** [comment] 2016-12-13 15:16
Hi Georg,

Thanks for bug report. Happily, we've been working on a fix for this already and I hope to get a release out to cpan shortly. Cheers!

**Comment by hornschorsch** [comment] 2016-12-14 18:38
I believe i am really to stupid for github and cpan. How can i install version 1.01?

```
# cpanm Selenium::Remote::Driver
Selenium::Remote::Driver is up to date. (1.00)
```

Kind Regards,
Georg

**Comment by gempesaw** [comment] 2016-12-14 20:56
Oh, sorry for the confusion! I usually release a [trial version](https://metacpan.org/release/GEMPESAW/Selenium-Remote-Driver-1.01-TRIAL) to let cpantesters kick the build around a bit before releasing an official version. The following should get you sorted:

    cpanm Selenium::Remote::Driver@1.01

FWIW, if I hadn't done the sneaky TRIAL business, then your command would've worked exactly as you expected!

**Comment by hornschorsch** [comment] 2016-12-15 11:33
Thanks for pointing me into the right direction! Unfortunately i am getting the same error as before:

```
Use of uninitialized value in hash element at /usr/local/share/perl5/Selenium/Remote/ErrorHandler.pm line 126.
Error while executing command: findElement at /usr/local/share/perl5/Selenium/Remote/Driver.pm line 313.
 at /usr/local/share/perl5/Selenium/Remote/Driver.pm line 313.
 at /usr/local/share/perl5/Selenium/Remote/Finders.pm line 23.
```

**Comment by hornschorsch** [comment] 2016-12-21 17:37
Sorry for annoying, but is there anything new regarding this issue?

Kind Regards,
Georg

**Comment by gempesaw** [comment] 2016-12-21 18:39
no worries. i haven't looked at it yet but i plan to do so today. cheers!

**Comment by gempesaw** [comment] 2016-12-26 20:35
Hm, can you upgrade your Firefox version, or is that impractical for your situation? I wish I could try it on the newest FF version of 50.1.0, but FWIW I can't reproduce the error against FF 49.0.1...

Although, it was FF48 that should've made the difference, I kind of doubt that a patch bump release would impact this...

**Comment by gempesaw** [comment] 2016-12-30 18:28
Oh, cool, one of the responses there holds the key:

```
RES: {"error":"invalid argument","message":"Unknown locator strategy name"}
```

Apparently name is an invalid strategy? That's actually news to me, I'll have to remove that strategy... I presume something has changed in the spec at some point. In the meantime, consider using CSS or xpath (or, I prefer using IDs if possible) to locate the element. Cheers!

**Comment by hornschorsch** [comment] 2017-01-01 09:14
Thanks and a happy new year!

with xpath it works! But this is really annoying and inconvenient.You always have to type `//input[\@name='user']"` instead of `"user"`...

And if i understand correctly, Selenium::Remote::Driver also uses geckodriver in the end, at least a geckodriver process is started, so how does it work there?

**Comment by gempesaw** [comment] 2017-01-01 21:08
I usually prefer CSS over xpath, where the syntax is _slightly_ cleaner

    $driver->find_element_by_css('[name=user]');

With S::R::D, presumably there's code that converts the invalid finding strategies to valid ones in the java standalone server. I should probably implement something similar in Selenium::Firefox, actually!

**Closed** 2017-02-01 21:52 UTC
