### ISSUE TITLE
SSL Certificate Error Handling in Firefox using Selenium::Firefox::Profile in Perl.

### ISSUE THREAD

**Issue by ojeje** [gempesaw/Selenium-Remote-Driver#311] opened 2017-03-30 21:06 UTC
I am running into issues with adding firefox certificate exception though Selenium::Firefox::Profile.

Here is the relevant part of my test code:

```
use Selenium::Remote::Driver;
use Selenium::Remote::Driver::Firefox::Profile;
use Selenium::Remote::WDKeys;
use Data::Dumper;
use Test::Most tests => 8;


## Pure Selenium::Remote::Driver
my $profile = Selenium::Remote::Driver::Firefox::Profile->new();
$profile->set_boolean_preference("accept_untrusted_certs" => 1);


my $driver = Selenium::Remote::Driver->new(
    'remote_server_addr' => 'localhost',
    'browser_name' => 'firefox',
 'accept_ssl_certs' => 'true',
 'firefox_profile' => $profile,
    'platform' => 'WINDOWS',
    'port' => '4444',
);
```

The problem is that I do not know for sure what the boolean preference name is.

I used "accept_untrusted_certs" but it did not work. Please help!

**Comment by gempesaw** [comment] 2017-04-04 02:00
Hullo, this looks like a duplicate of #277, which was a bug in [geckodriver](https://github.com/mozilla/geckodriver/issues/93), and tracked in the [firefox bug tracker](https://bugzilla.mozilla.org/show_bug.cgi?id=1103196). It was recently resolved, and one of the authors helpfully wrote up a [blog post](https://www.hskupin.info/2017/01/23/using-selenium-and-webdriver-to-interact-with-insecure-ssl-pages-in-firefox/) explaining the usage. 

I think the short version of it was you need to use FF52 (which is in beta soon? or now? or out already? i don't know...), and the preference name is `acceptInsecureCerts`. Good luck!

**Closed** 2017-04-04 16:12 UTC

**Comment by ojeje** [comment] 2017-04-04 22:08
Thanks @gempesaw. I have read the blog post and I am working on adapting the concept of his code to Perl. I was all the while on FF52 on Windows 10.
